platform :ios, '9.0'

target :'iOS Example' do
#Foudation依赖库
    pod 'SDWebImage', '~> 4.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Realm'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'MJRefresh'

#第三方pod

end
